FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

# ビルド用にdevDependenciesもインストール
RUN npm install

COPY . .

RUN npm run build

# 本番用にdevDependenciesを削除
RUN npm prune --production

EXPOSE 3001

CMD ["npm", "start"] 
